#!/usr/bin/env python3

import os
import sys


def docker_exec(service, cmd):
    os.system(f"docker compose exec {service} bash -c '{cmd}'")


def server_init():
    # TODO: Actually set up the survey and queries here, removing them if they
    #       already exist.
    pass


def client_exec(cmd):
    docker_exec("client", cmd)


def client_init():
    # TODO: Send more reasonable data - different for each client.
    client_exec(". ./dbus-env.sh && dbus-send --type=method_call "
                "--dest=org.privact.client / "
                "org.privact.client.Data.submit_data_point "
                "string:foo string:bar")



commands = {
    "server-init": server_init,
    "client-init": client_init
}


def show_usage():
    print(f"Usage: {sys.argv[0]} {'|'.join(commands.keys())}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        show_usage()
        sys.exit(1)
    command = sys.argv[1]
    if command not in commands:
        show_usage()
        sys.exit(2)

    commands[command]()
