services:
  web:
    environment:
      - "DATABASE_URL=postgresql://dekufserver:dekufserver@db/dekufserver"
    build: server
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "poetry run ./manage.py migrate &&
             poetry run ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8080:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dekufserver
      - POSTGRES_PASSWORD=dekufserver
      - POSTGRES_DB=dekufserver
      # Used for the healthcheck
      - PGUSER=dekufserver
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
    postgres_data:
