services:
    server:
        build: server
        ports:
            - "8080:8000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/api/surveys"]
            start_period: 5s
            interval: 60s
            timeout: 10s
            retries: 5
        command: >
            sh -c "poetry run ./manage.py migrate &&
                   poetry run ./manage.py runserver 0.0.0.0:8000"

    client:
        build: client
        depends_on:
            server:
                condition: service_healthy
        scale: 4
        environment:
            DEKUF_CLIENT_SERVER_URL: "http://server:8000"
        command: >
            sh -c 'echo "export $(dbus-launch)" > dbus-env.sh
                   . ./dbus-env.sh
                   make run-daemon'
