# Generated by Django 5.0.3 on 2024-03-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Commissioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_key", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="QueryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_key", models.CharField(max_length=100)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commissioners",
                    models.ManyToManyField(to="core.commissioner"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commissioners",
                    models.ManyToManyField(to="core.commissioner"),
                ),
            ],
        ),
        migrations.DeleteModel(name="JSONData"),
        migrations.AddField(
            model_name="query",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to="core.survey",
            ),
        ),
        migrations.AddField(
            model_name="queryresponse",
            name="survey_response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queryResponses",
                to="core.surveyresponse",
            ),
        ),
    ]
