# Generated by Django 4.2.11 on 2024-05-30 14:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_surveysignup")]

    operations = [
        migrations.CreateModel(
            name="AggregationGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.surveysignup",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.survey",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="surveysignup",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.aggregationgroup",
            ),
        ),
    ]
