# Generated by Django 4.2.11 on 2024-05-06 10:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_survey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="cohorts",
            field=models.JSONField(
                default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
