# Generated by Django 4.2.11 on 2024-06-04 14:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_aggregationgroup_surveysignup_group")]

    operations = [
        migrations.CreateModel(
            name="ClientToDelegateMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delegate", models.UUIDField(editable=False)),
                ("content", models.JSONField(editable=False)),
                (
                    "group",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.aggregationgroup",
                    ),
                ),
            ],
        )
    ]
