# Generated by Django 4.2.11 on 2024-06-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_clienttodelegatemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveysignup",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aggregation_group",
                to="core.aggregationgroup",
            ),
        ),
    ]
