# Generated by Django 4.2.13 on 2024-06-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_alter_surveysignup_group")]

    operations = [
        migrations.AlterField(
            model_name="aggregationgroup",
            name="delegate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.surveysignup",
            ),
        ),
        migrations.AlterField(
            model_name="aggregationgroup",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="core.survey"
            ),
        ),
        migrations.AlterField(
            model_name="surveysignup",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.aggregationgroup",
            ),
        ),
    ]
