# Generated by Django 4.2.13 on 2024-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_aggregationgroup_delegate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="group_count",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="survey",
            name="group_size",
            field=models.IntegerField(default=2),
        ),
    ]
