# Generated by Django 4.2.13 on 2024-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_surveysignup_public_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clienttodelegatemessage",
            old_name="delegate",
            new_name="delegate_id",
        ),
        migrations.AlterField(
            model_name="clienttodelegatemessage",
            name="content",
            field=models.TextField(editable=False),
        ),
    ]
