# Generated by Django 4.2.13 on 2024-08-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0010_rename_delegate_clienttodelegatemessage_delegate_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregationgroup",
            name="aggregation_private_key_p",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aggregationgroup",
            name="aggregation_private_key_q",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aggregationgroup",
            name="aggregation_public_key_g",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aggregationgroup",
            name="aggregation_public_key_n",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
