# Generated by Django 4.2.13 on 2024-08-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_aggregationgroup_aggregation_private_key_p_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("key", models.CharField(max_length=50, unique=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "INTEGER"), (2, "DECIMAL")]
                    ),
                ),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("precision", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="query",
            name="data_key",
        ),
        migrations.AddField(
            model_name="query",
            name="data_point",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.datapoint",
            ),
            preserve_default=False,
        ),
    ]
