# Generated by Django 4.2.13 on 2024-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_load_fixture_data_points_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="number_participants",
        ),
        migrations.AddField(
            model_name="survey",
            name="number_participants",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="number_participants",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
